// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OddsCollector.Data;

#nullable disable

namespace OddsCollector.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    partial class ApplicationDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OddsCollector.Models.Odd", b =>
                {
                    b.Property<string>("SportEventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bookmaker")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("AwayOdd")
                        .HasColumnType("float");

                    b.Property<double>("DrawOdd")
                        .HasColumnType("float");

                    b.Property<double>("HomeOdd")
                        .HasColumnType("float");

                    b.HasKey("SportEventId", "LastUpdate", "Bookmaker");

                    b.ToTable("Odds");
                });

            modelBuilder.Entity("OddsCollector.Models.SportEvent", b =>
                {
                    b.Property<string>("SportEventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommenceTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportEventId");

                    b.ToTable("SportEvents");
                });

            modelBuilder.Entity("OddsCollector.Models.Odd", b =>
                {
                    b.HasOne("OddsCollector.Models.SportEvent", null)
                        .WithMany("Odds")
                        .HasForeignKey("SportEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OddsCollector.Models.SportEvent", b =>
                {
                    b.Navigation("Odds");
                });
#pragma warning restore 612, 618
        }
    }
}
